name: ACR1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Testing"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Testing..."
