name: C3_workflow

on:
  pull_request_target:
    branches:
      - develop
  push:

jobs:
  before-publish-upload-artifact:
    runs-on: ubuntu-20.04
    steps:
      - name: Create artifact A1
        run: echo "This is an artifact from C3 4" > report.txt

      - name: Uploading A1 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-report
          path: report.txt